# OSEMN Exercises

In [8]:
%matplotlib inline
import pandas as pd
import numpy as np
import numpy.random as npr

1\. Create a random list of numbers and then save it to a text file named "simple_data.txt"

In [9]:
a = [npr.rand() for i in range (0,1000)]
fname = "/Users/lorenzobarbiero/data/randlist.txt"
np.savetxt(fname, a, delimiter=' ', newline='\n')
#print (a)

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [10]:
b = npr.rand(5,5)
fname = "/Users/lorenzobarbiero/data/randmat.txt"
np.savetxt(fname, b, delimiter=' ', newline='\n')
print(b)

[[0.70884465 0.65863403 0.44688876 0.6350147  0.7896461 ]
 [0.674916   0.40694839 0.14792786 0.02389895 0.61227404]
 [0.1051184  0.18510833 0.10096192 0.8823635  0.92988312]
 [0.13412435 0.16447723 0.81116468 0.23084294 0.14135733]
 [0.33940027 0.18124801 0.33046679 0.68716321 0.62869897]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [28]:
file_name = "/Users/lorenzobarbiero/data/randmat.txt"

# mode can be specified for writing, reading or both
with open(file_name) as f:
    # print-out the whole file
    # print (f.read()) 
    for line in f:
        line2 = ""
        # print line by line
        # print (line)
        # each line is a string, you need to split it yourself
        for c in line.split():
            c = c + ","
            line2 += c
        line = line2
            #print(c) # check the functionalities of the split() method
        print(line)
        
fname = "/Users/lorenzobarbiero/data/csvtry.csv"
np.savetxt(fname,f, delimiter=',', newline='\n')

6.227194416767009022e-01,7.084872272994906517e-01,4.271078082381134511e-01,2.760353385679299443e-01,3.362586557216449279e-01,
2.561196912020247130e-02,8.885129680292244148e-01,8.972057472170569259e-01,4.315196680542643382e-02,3.641662442763372587e-01,
3.325405206119279589e-01,4.126041379049216751e-02,7.835271671876610222e-01,4.445702609962625118e-01,3.735031981565852810e-01,
2.139780048842060411e-01,2.557137842887798884e-01,3.271704775729422643e-02,9.103022523185129167e-01,8.682969570351962707e-01,
6.949403756208586413e-01,7.301852375071468115e-01,7.286060577817790040e-01,8.748406471732451672e-01,7.163886942102107858e-01,


ValueError: Expected 1D or 2D array, got 0D array instead

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [11]:
with open("credit_card.dat", "rb") as file:
    data = file.read()

card_numbers = []
number = ""
for i in range(0, len(data), 6):
    if len(number) == 19:
        card_numbers.append(number[0:16])
        number = ""
    # Get the 6-bit number
    num = data[i:i+6]

    # Convert the number to an integer
    num = int.from_bytes(num, "big")

    if len(number) < 19:
        # Remove the last 4 bits (padding) if the last character
        if len(number) == 18:
            num = num >> 4
        # Convert the number to a character
        char = chr(num)

        # Add the character to the current card number
        number += char

print(card_numbers)



OverflowError: Python int too large to convert to C int

In [46]:
file_name = "/Users/lorenzobarbiero/data/credit_card.dat"

from functools import partial
with open(file_name) as f:
    for line in f:
        for chunk in iter(partial(line, 6), '\n'):
            print(repr(chunk), len(chunk))

'''with open(file_name) as f:
    print(chr(int(f.read(4))))
    for line in f:
        #print(line.read(4))
        for c in line.split():
            mask = 0
            a = ""
            while (mask<6):
                a += c
                mask += 1
            num = chr(int(a))'''
        #print (line)'''

TypeError: the first argument must be callable

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.