# OSEMN Exercises

In [4]:
%matplotlib inline
import pandas as pd
import numpy as np
import numpy.random as npr

1\. Create a random list of numbers and then save it to a text file named "simple_data.txt"

In [9]:
a = [npr.rand() for i in range (0,1000)]
fname = "/Users/lorenzobarbiero/data/randlist.txt"
np.savetxt(fname, a, delimiter=' ', newline='\n')
#print (a)

[0.6313250792123039, 0.7893518140444814, 0.3605213540278289, 0.25085825858768895, 0.7959388487718233, 0.44628577952960313, 0.13824938536614884, 0.48824712935529857, 0.6706557312939196, 0.8028798180184169, 0.6969184872751613, 0.975118123658329, 0.8642905650932049, 0.6772902133550653, 0.5361666310924633, 0.6909051429499233, 0.9759282792026792, 0.6209609575454862, 0.4677688854984021, 0.1598405643028986, 0.18603114523797715, 0.2613970086252104, 0.7051580333222426, 0.3203154705136104, 0.5714265486944107, 0.2351647144616429, 0.5300522612989056, 0.6796070706403815, 0.5768908106833609, 0.3211653588890472, 0.5886379259249247, 0.024586187768044776, 0.03813213661207604, 0.3346992318230949, 0.27966154628927764, 0.019350002121543253, 0.3798385001838681, 0.1779509054279529, 0.7273897127268669, 0.6214127887241454, 0.5377180922959087, 0.7668402849054189, 0.975754097326745, 0.7369203555569284, 0.22473988487600782, 0.3510088958822364, 0.7206878516432913, 0.8651344428745779, 0.06867795941652632, 0.311556

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [11]:
b = npr.rand(5,5)
fname = "/Users/lorenzobarbiero/data/randmat.txt"
np.savetxt(fname, b, delimiter=' ', newline='\n')
print(b)

[[0.62271944 0.70848723 0.42710781 0.27603534 0.33625866]
 [0.02561197 0.88851297 0.89720575 0.04315197 0.36416624]
 [0.33254052 0.04126041 0.78352717 0.44457026 0.3735032 ]
 [0.213978   0.25571378 0.03271705 0.91030225 0.86829696]
 [0.69494038 0.73018524 0.72860606 0.87484065 0.71638869]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [28]:
file_name = "/Users/lorenzobarbiero/data/randmat.txt"

# mode can be specified for writing, reading or both
with open(file_name) as f:
    # print-out the whole file
    # print (f.read()) 
    for line in f:
        line2 = ""
        # print line by line
        # print (line)
        # each line is a string, you need to split it yourself
        for c in line.split():
            c = c + ","
            line2 += c
        line = line2
            #print(c) # check the functionalities of the split() method
        print(line)
        
fname = "/Users/lorenzobarbiero/data/csvtry.csv"
np.savetxt(fname,f, delimiter=',', newline='\n')

6.227194416767009022e-01,7.084872272994906517e-01,4.271078082381134511e-01,2.760353385679299443e-01,3.362586557216449279e-01,
2.561196912020247130e-02,8.885129680292244148e-01,8.972057472170569259e-01,4.315196680542643382e-02,3.641662442763372587e-01,
3.325405206119279589e-01,4.126041379049216751e-02,7.835271671876610222e-01,4.445702609962625118e-01,3.735031981565852810e-01,
2.139780048842060411e-01,2.557137842887798884e-01,3.271704775729422643e-02,9.103022523185129167e-01,8.682969570351962707e-01,
6.949403756208586413e-01,7.301852375071468115e-01,7.286060577817790040e-01,8.748406471732451672e-01,7.163886942102107858e-01,


ValueError: Expected 1D or 2D array, got 0D array instead

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [46]:
file_name = "/Users/lorenzobarbiero/data/credit_card.dat"

from functools import partial
with open(file_name) as f:
    for line in f:
        for chunk in iter(partial(line, 6), '\n'):
            print(repr(chunk), len(chunk))

'''with open(file_name) as f:
    print(chr(int(f.read(4))))
    for line in f:
        #print(line.read(4))
        for c in line.split():
            mask = 0
            a = ""
            while (mask<6):
                a += c
                mask += 1
            num = chr(int(a))'''
        #print (line)'''

TypeError: the first argument must be callable

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.